<a href="https://colab.research.google.com/github/NataliaWrzesinska/data-science-bootcamp/blob/main/Kopia_notatnika_template.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello colab")

Hello colab


In [ ]:
import numpy as np
np.__version__

'1.22.4'

In [ ]:
dir(np)

In [ ]:
help(np.array)

In [ ]:
x = np.array([1,3])
x

array([1, 3])

In [ ]:
y = np.array([[1, 3], [2,4]])
y

array([[1, 3],
       [2, 4]])

In [ ]:
z = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
z

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
X = np.array([1,2], dtype="complex")
X

array([1.+0.j, 2.+0.j])

In [ ]:
np.zeros(shape=(4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.ones(shape=(4, 10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
 np.arange(start = 10, stop = 150, step = 10)

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140])

In [ ]:
 np.linspace(start = 0, stop = 10, num = 10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [ ]:
np.random.seed(0)


In [ ]:
np.random.randn()

1.8334382741158555

In [ ]:
np.random.randn(10)


array([-0.01997767,  0.81273075,  0.42826455, -0.71546885, -0.91174063,
       -1.17204543,  0.28528831, -2.22582582,  0.51323029, -0.3280537 ])

In [ ]:
np.random.randn(10, 4)


array([[ 1.77871175, -0.2381877 , -1.84271865,  0.57965943],
       [ 1.0583309 , -0.69352204, -0.70292807, -1.13045342],
       [ 0.40240855,  0.71195403, -0.33325279,  0.81307244],
       [ 2.01498943,  0.6002832 ,  0.24677043, -0.15639238],
       [-0.22928204,  0.25538475,  2.88524273,  1.4575089 ],
       [-1.97948893, -1.44406488, -0.45811137,  0.50853886],
       [ 0.27686438, -1.03289812, -0.18008809, -1.52286392],
       [-0.0732493 , -1.55132669, -0.27163414, -0.52738059],
       [ 0.37946267,  1.54440411, -0.42992406, -0.43710114],
       [ 1.3256565 ,  0.41431307,  3.05294067,  0.56614205]])

array([61, 41, 75, 24, 22, 71, 48, 32, 98, 72])

In [ ]:
np.random.choice([1, 4, 5, 8])

4

In [ ]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.random.shuffle(data)
data

array([5, 8, 7, 2, 3, 4, 1, 6, 0, 9])

In [ ]:
np.exp(1)

2.718281828459045

In [ ]:
np.sqrt(9)

3.0

In [ ]:
np.all([2, 3, 1])

True

In [ ]:
np.any([2, 3, 1])

True

In [ ]:
v1 = np.array([0, 4])
v1

array([0, 4])

In [ ]:
np.linalg.norm(v1)

4.0

In [ ]:
V2 = np.array([-10, 10, 13])

In [ ]:
np.linalg.norm(V2)

19.209372712298546

In [ ]:
p = np.array([0, 4, 6])
q = np.array([1, 5, 6])

In [ ]:
np.linalg.norm(p-q)

1.4142135623730951